# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: phonebook.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fphonebook.proto\x12\tphonebook\x1a\x1bgoogle/protobuf/empty.proto\"f\n\x05\x45ntry\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x12\n\npatronymic\x18\x03 \x01(\t\x12\x14\n\x0cphone_number\x18\x04 \x01(\t\x12\x0c\n\x04note\x18\x05 \x01(\t2\xe7\x01\n\x10PhoneBookService\x12\x34\n\x08\x41\x64\x64\x45ntry\x12\x10.phonebook.Entry\x1a\x16.google.protobuf.Empty\x12\x37\n\x0b\x44\x65leteEntry\x12\x10.phonebook.Entry\x1a\x16.google.protobuf.Empty\x12\x33\n\x0bSearchEntry\x12\x10.phonebook.Entry\x1a\x10.phonebook.Entry0\x01\x12/\n\tViewEntry\x12\x10.phonebook.Entry\x1a\x10.phonebook.Entryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'phonebook_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ENTRY']._serialized_start=59
  _globals['_ENTRY']._serialized_end=161
  _globals['_PHONEBOOKSERVICE']._serialized_start=164
  _globals['_PHONEBOOKSERVICE']._serialized_end=395
# @@protoc_insertion_point(module_scope)
